if(CMAKE_SKIP_INSTALL_RULES)
  return()
endif()
include(GNUInstallDirs)
install(TARGETS tsds_lib
  EXPORT tsdsTargets
  FILE_SET CXX_MODULES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/tsds
  FILE_SET HEADERS DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/tsds
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/tsds
)
install(FILES
  ${PROJECT_BINARY_DIR}/tsds_export.h
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/tsds
)
install(EXPORT tsdsTargets
  FILE tsdsTargets.cmake
  NAMESPACE tsds::
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/tsds
)
include(CMakePackageConfigHelpers)
write_basic_package_version_file(
  "${PROJECT_BINARY_DIR}/tsdsConfigVersion.cmake"
  VERSION ${PROJECT_VERSION}
  COMPATIBILITY SameMajorVersion
)

install(FILES "${CMAKE_CURRENT_LIST_DIR}/install-config.cmake"
  RENAME "tsdsConfig.cmake"
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/tsds
)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/tsdsConfigVersion.cmake"
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/tsds)
